function write_metric(fid, dn, mn, bl, metrics)
    fprintf(fid, '%s,%s,%s,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f\n', ...
        dn, mn, bl, metrics(1), metrics(2), metrics(3), metrics(4),...
        metrics(5), metrics(6)...
    );
end